# Blog info
blog_name: Apparition
slogan: petals on a wet, black bough.
url: https://www.rosetiger.info

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /favicon.png

# For seo
keywords: Java,Spring Cloud,microservice,微服务,后端开发,Spring,MySQL,backend,前端,frontend,JavaScript

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  # - name: Project
  #   url: /project/
  #   target_blank: true #在新页面打开
  - name: Github
    url: https://github.com/esahcorp
    target_blank: true
  - name: Instagram
    url: https://www.instagram.com/etiktsol/
    target_blank: true

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 友链
    url: /link/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  # - name: RSS
  #   url: /atom.xml
  #   target_blank: true # 在新页面打开
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 盒子

search_slogan:
  isShow: true # true|fase
  text: 吾诗已成，不可毁灭。

link_slogan:
  isShow: true # true|fase
  text: 交换友链可以邮件 lostkite@outlook.com


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: false
  btn_text: 支持一下
  tip: 扫一扫，支持forsigner
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/qr-wechat.png
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/qr-alipay.png




post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
personal_style: /css/personal-style.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: POST  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics: 57e94d016e201fba3603a8a2b0263af0

# Comment service
# disqus_shortname: forsigner
# gitalk_shortname: forsigner
# hypercomments_id: 89821
# gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

#有言用户编号
#uyan_key:

# changyan_appid:
# changyan_appkey:

# gitment comment service
# gitment:
#     on: false  # true | false  这里开启
#     owner: # Your GitHub ID. Required.
#     repo: # The repository to store your comments. Make sure you're repo's owner. Required.
#     oauth: # An object contains your client ID and client secret. Required.
#         client_id: # GitHub client ID. Required.
#         client_secret: # GitHub client secret. Required.
#     id: # An optional string to identify your page. Default location.href.
#     title: # An optional title for your page, used as issue's title. Default document.title.
#     link: # An optional link for your page, used in issue's body. Default location.href.
#     desc: # An optional description for your page, used in issue's body. Default ''.
#     labels: # An optional array of labels your want to add when creating the issue. Default [].
#     theme: # An optional Gitment theme object. Default gitment.defaultTheme.
#     perPage: # An optional number to which comments will be paginated. Default 20.
#     maxCommentHeight: # An optional number to limit comments' max height, over which comments will be folded. Default 250.

# Valine comment system  https://valine.js.org
valine:
  enable: true # 如果使用valine，请设置改之为true
  appid: Hpdh6pLO3faHO20IYwqb4anw-9Nh9j0Va # your leancloud application appid
  appkey: Hy7N6SOObaIgAyyvKPg9xNGj # your leancloud application appkey
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Thanks for you feedback # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size




# 不蒜子,文章访问量统计和显示
busuanzi: true

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "人生如逆旅，我亦是行人."
    - "代码是有限的，功能是无限的。"
    - "尔曹身与名俱灭，不废江河万古流."
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@esahcorp"
    text_value_url: https://github.com/esahcorp
  # - type: Instagram
  #   icon: icon-instagram
  #   text_key: Instagram
  #   text_value: "@etiktsol"
  #   text_value_url: https://www.instagram.com/etiktsol/
  - type: mail
    icon: icon-mail
    text_key: Email
    text_value: "lostkite@outlook.com"
    text_value_url: mailto:lostkite@outlook.com
  - type: location
    icon: icon-location
    text_value: 上海

link:
  - name: sywy
    info: 大道至简，衍化至繁
    url: https://sywy1.github.io/
    avatar: https://avatars2.githubusercontent.com/u/28619699?s=100&v=3


project:
  # - type: personal
    # name: fexo
    # url: https://github.com/forsigner/fexo
    # intro: A minimalist design theme for hexo
  # - type: company
  #   name: Fexo
  #   url: https://github.com/forsigner/fexo
  #   intro: A minimalist design theme for hexo
  # - type: personal
  #   name: beside
  #   url: https://github.com/forsigner/beside
  #   intro: I need you beside me
  # - type: personal
  #   name: web-fontmin
  #   url: https://github.com/forsigner/web-fontmin
  #   intro: 字体子集化，在线提取你需要的字体
  # - type: personal
  #   name: magic-check
  #   url: https://github.com/forsigner/magic-check
  #   intro: Beautify Radio and Checkbox with pure CSS
  # - type: personal
  #   name: nice-bar
  #   url: https://github.com/forsigner/nice-bar
  #   intro: A nice and lightweight scrollbar
  # - type: personal
  #   name: angular-nice-bar
  #   url: https://github.com/forsigner/angular-nice-bar
  #   intro: A nice and lightweight scrollbar in Angular
  # - type: personal
  #   name: fo-popover
  #   url: https://github.com/forsigner/fo-popover
  #   intro: A nice popover for Angular
  # - type: personal
  #   name: fo-tooltip
  #   url: A nice tooltip for Angular
  #   intro: https://github.com/forsigner/fo-tooltip
  # - type: personal
  #   name: fo-modal
  #   url: https://github.com/forsigner/fo-modal
  #   intro: A nice modal for Angular
  # - type: personal
  #   name: mocer
  #   url: https://github.com/forsigner/mocer
  #   intro: Setup a mock server easily
  # - type: personal
  #   name: node-pngdefry
  #   url: https://github.com/forsigner/node-pngdefry
  #   intro: Repairing iPhone fried PNGs using Node.js
  # - type: personal
  #   name: ng-simditor
  #   url: https://github.com/forsigner/ng-simditor
  #   intro: Angular directive for simditor
